<!--startfooter-->
<div id="footer">
  <div id="mainfooter">
    <div id="quicklink">
      <h3>Quick Link</h3>
      <ul>
        <li>
          <a href="faq.aspx">FAQ</a>
        </li>
        <li>
          <a href="contact-us.aspx">Contact Us</a>
        </li>
        <li>
          <a href="privacy-policy.aspx">Privacy Policy</a>
        </li>
        <li>
          <a href="anti-span.aspx">Anti Spam Policy</a>
        </li>
        <li>
          <a href="support.aspx">Support</a>
        </li>
      </ul>
    </div>
    <div id="staywith">
      <h3>Stay with us</h3>
      <ul>
        <li class="facebook">
          <a href="#">Facebook</a>
        </li>
        <li class="twetter">
          <a href="#">Twitter</a>
        </li>
        <li class="yuotube">
          <a href="#">Youtube</a>
        </li>
      </ul>
    </div>
    <div id="copyright">
      <div id="footerlogo">
        <a href="#">
          <img src="images/footer-logo-img.jpg" width="122" height="60" border="0" />
        </a>
        <div class="spacer">
        </div>
      </div>
      <div id="footrpara">
        <p>
          &copy; Copyright 2011. fneasy. All rights Reserved
        </p>
        <p class="cyberplex">
          Developed by <a href="http://www.fneasy.com" target="_blank">Fneasy Software</a>
        </p>
      </div>
    </div>
    <div class="spacer">
    </div>
  </div>
</div>
<!--endfooter-->